default_steps: &default_steps
    steps:
      - checkout
      - run:
          name: install dependencies
          command: |
            python --version
            python -m venv venv
            . venv/bin/activate
            pip install pytest
            pip install .

            mkdir binaries
            cd binaries
            wget http://mersenneforum.org/gimps/mprime276-linux64.tar.gz
            tar -xvzf mprime276-linux64.tar.gz
            mv mprime ../venv/bin/
            cd -
            rm -rf binaries
      - run:
          name: run tests
          command: |
            . venv/bin/activate
            ls -l
            python -m pytest


version: 2
jobs:
  python3.6.1:
    docker:
      - image: circleci/python:3.6.1
    working_directory: ~/repo
    <<: *default_steps
  python3.7.3:
    docker:
      - image: circleci/python:3.7.3
    working_directory: ~/repo
    <<: *default_steps
  python3.5.7:
    docker:
      - image: circleci/python:3.5.7
    working_directory: ~/repo
    <<: *default_steps

workflows:
    version: 2
    build_and_test:
      jobs:
        - python3.6.1
        - python3.7.3
        - python3.5.7
